#!/usr/bin/env bash
set -e
set -x

main() {
  install_git
  clone_kegbot
  install_salt_minion
  highstate
}

install_git() {
  apt-get update -y
  apt-get install -y git-all
}

clone_kegbot() {
  mkdir -p /srv/repos
  pushd /srv/repos
  git clone https://github.com/zackhsi/kegbot-aws.git
  popd
}

install_salt_minion() {
  # Install salt
  curl -L https://bootstrap.saltstack.com | sh -s

  # Configure minion
  cat <<EOF | tee /etc/salt/minion
failhard: True
file_client: local
state_verbose: False
state_output: mixed
log_level: info
file_roots:
  base:
    - /srv/repos/kegbot-aws/salt/states
pillar_roots:
  base:
    - /srv/repos/kegbot-aws/salt/pillar
EOF
}

highstate() {
  salt-call state.highstate
}

main
